### PR TITLE
Update call-for-posters.md Important Dates

### PR DESCRIPTION
**Pull request by nicolemarsaglia**
2024 poster dates

### CODE REVIEW

**Comment by nicolemarsaglia** [comment]
Updated the Important Dates on the Posters Page. @hfstudio , if you could approve this when you get a chance that would be great, thank you!

**Comment by nicolemarsaglia** [comment]
Hi @hfstudio and @ghweber , we have started to get emails asking about poster submission deadlines, if this could get merged in that would be great. Thanks!

**Comment by hfstudio** [comment]
> Hi @hfstudio and @ghweber , we have started to get emails asking about poster submission deadlines, if this could get merged in that would be great. Thanks!

Done!

**Comment by hfstudio** [comment]
Done!

**Pull request merged**
